"""reviews table

Revision ID: 3ab724e27a47
Revises: e72f5d023b69
Create Date: 2024-02-13 21:23:05.917504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab724e27a47'
down_revision = 'e72f5d023b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
