"""moved tabales to models

Revision ID: 5eba313b747b
Revises: 75f16de55cbb
Create Date: 2024-02-13 21:57:00.939536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eba313b747b'
down_revision = '75f16de55cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_users',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'customer_id')
    )
    op.add_column('reviews', sa.Column('star_rating', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.INTEGER(), nullable=True))
    op.drop_column('reviews', 'star_rating')
    op.drop_table('restaurant_users')
    # ### end Alembic commands ###
