"""moved tabales to models

Revision ID: 75f16de55cbb
Revises: 1bf8dd81778c
Create Date: 2024-02-13 21:53:21.157196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f16de55cbb'
down_revision = '1bf8dd81778c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
