"""sqlite

Revision ID: fa6101a1a396
Revises: 5eba313b747b
Create Date: 2024-02-14 18:55:59.656214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6101a1a396'
down_revision = '5eba313b747b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
